### ISSUE TITLE
please use lifecycleOwner = this@ContributorsFragment.viewLifecycleOwner

### ISSUE THREAD

**Issue by ROMVL** [valentynsmetanin/CoroutinesSandbox#1]
https://github.com/valentynsmetanin/CoroutinesSandbox/blob/b48681fbfa615b58aaaba89550cac151b0e72208/app/src/main/java/com/svapp/coroutinessandbox/presentation/contributors/ContributorsFragment.kt#L24

**Comment by valentynsmetanin** [comment]
Added viewLifecycleOwner as lifecycleOwner
